"@context":

ontologies:

## EFO

  - id: efo
    preferredPrefix: EFO
    title: Experimental Factor Ontology
    uri: http://www.ebi.ac.uk/efo
    description: "The Experimental Factor Ontology (EFO) provides a systematic description of many experimental variables available in EBI databases, and for external projects such as the NHGRI GWAS catalogue. It combines parts of several biological ontologies, such as anatomy, disease and chemical compounds. The scope of EFO is to support the annotation, analysis and visualization of data handled by many groups at the EBI and as the core ontology for the Centre for Therapeutic Validation (CTTV)"
    homepage: http://www.ebi.ac.uk/efo
    mailing_list: efo-users@lists.sourceforge.net
    definition_property:
      - http://www.ebi.ac.uk/efo/definition
    synonym_property:
      - http://www.ebi.ac.uk/efo/alternative_term
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
      - http://purl.obolibrary.org/obo/RO_0002202
    hidden_property:
      - http://www.ebi.ac.uk/efo/has_flag
    base_uri:
      - http://www.ebi.ac.uk/efo/EFO_
    isInferred: false
    classify: true
    oboSlims: false
    products:
     - id: http://www.ebi.ac.uk/efo/efo.owl
       type: owl:Ontology


## ORDO

  - id: ordo
    preferredPrefix: ORDO
    description: "The Orphanet Rare Disease ontology (ORDO) is jointly developed by Orphanet and the EBI to provide a structured vocabulary for rare diseases capturing relationships between diseases, genes and other relevant features which will form a useful resource for the computational analysis of rare diseases.
                  It derived from the Orphanet database (www.orpha.net ) , a multilingual database dedicated to rare diseases populated from literature and validated by international experts.
                  It integrates a nosology (classification of rare diseases), relationships (gene-disease relations, epiemological data) and connections with other terminologies (MeSH, UMLS, MedDRA),databases (OMIM, UniProtKB, HGNC, ensembl, Reactome, IUPHAR, Geantlas) or classifications (ICD10)."
    title: Orphanet Rare Disease Ontolog
    uri: http://www.orpha.net/ontology/orphanet.owl
    definition_property:
      - http://www.ebi.ac.uk/efo/definition
    synonym_property:
      - http://www.ebi.ac.uk/efo/alternative_term
    hidden_property:
      - http://www.ebi.ac.uk/efo/has_flag
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    base_uri:
      - http://www.orpha.net/ORDO/Orphanet_
    isInferred: false
    classify: true
    oboSlims: false
    products:
     - id: http://www.orphadata.org/data/ORDO/ordo_orphanet.owl
       type: owl:Ontology

## TEDDY

  - id: teddy
    preferredPrefix: TEDDY
    description: "TEDDY is an ontology for dynamical behaviours, observable dynamical phenomena, and control elements of bio-models and biological systems in Systems and Synthetic Biology."
    title: "Terminology for Description of Dynamics"
    uri: http://identifiers.org/teddy/
    definition_property:
      - http://www.w3.org/2004/02/skos/core#definition
    synonym_property:
      - http://www.w3.org/2004/02/skos/core#altLabel
    base_uri:
      - http://identifiers.org/teddy/TEDDY_
    isInferred: true
    classify: false
    oboSlims: false
    products:
     - id: http://www.biomodels.net/teddy/TEDDY
       type: owl:Ontology

## EDAM

  - id: edam
  preferredPrefix: EDAM
  title: EMBRACE Data and Methods
  uri: http://edamontology.org
  description: "EDAM is a simple ontology of well established, familiar concepts that are prevalent within bioinformatics, including types of data and data identifiers, data formats, operations and topics. EDAM provides a set of terms with synonyms and definitions - organised into an intuitive hierarchy for convenient use."
  homepage: http://edamontology.org
  mailing_list: edam@elixir-dk.org
  definition_property:
    - http://www.geneontology.org/formats/oboInOwl#hasDefinition
  synonym_property:
    - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
  base_uri:
    - http://edamontology.org/data_
  isInferred: true
  classify: false
  oboSlims: false
  products:
    - id: http://edamontology.org/EDAM.owl   ### This is the download URL
      type: owl:Ontology

## CCO

  - id: cco
  preferredPrefix: CCO
  title: Cell Cycle Ontology
  uri: http://purl.obolibrary.org/obo/cco
  description: "The Cell Cycle Ontology extends existing ontologies for cell cycle knowledge building a resource that integrates and manages knowledge about the cell cycle components and regulatory aspects."
  homepage: http://www.semantic-systems-biology.org/apo
  mailing_list: vladimir.n.mironov@gmail.com
  definition_property:
    - http://purl.obolibrary.org/obo/IAO_0000115
  synonym_property:
    - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
  base_uri:
    - http://purl.obolibrary.org/obo/CCO_
  isInferred: true
  classify: false
  oboSlims: true
  products:
    - id: http://www.nt.ntnu.no/users/mironov/ontology/CCO/cco.obo   ### This is the download URL
      type: obo:Ontology

## CMPO

  - id: cmpo
  preferredPrefix: CMPO
  title: Cellular Microscopy Phenotype Ontology
  uri: http://www.ebi.ac.uk/cmpo
  description: "CMPO is a species neutral ontology for describing general phenotypic observations relating to the whole cell, cellular components, cellular processes and cell populations."
  homepage: http://www.ebi.ac.uk/cmpo
  mailing_list: jupp@ebi.ac.uk
  definition_property:
    - http://purl.obolibrary.org/obo/IAO_0000115
  synonym_property:
    - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
  base_uri:
    - http://www.ebi.ac.uk/cmpo/CMPO_
  isInferred: true
  classify: false
  oboSlims: true
  products:
    - id: http://www.ebi.ac.uk/cmpo.owl   ### This is the download URL
      type: obo:Ontology
